// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHG0aPNQCllSqT9Oy97l1tO1ATmrAVzA',
    appId: '1:730513218017:web:f2c70f90d28d6ac85cdaa0',
    messagingSenderId: '730513218017',
    projectId: 'data-login-6101e',
    authDomain: 'data-login-6101e.firebaseapp.com',
    storageBucket: 'data-login-6101e.appspot.com',
    measurementId: 'G-XKBL569T34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHK4B67JKOPrM_FnF1ONcvmf88MsZhEc',
    appId: '1:730513218017:android:ac3e192fba5f6bee5cdaa0',
    messagingSenderId: '730513218017',
    projectId: 'data-login-6101e',
    storageBucket: 'data-login-6101e.appspot.com',
  );
}
